name: habitos_saludables
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0

  # State Management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # Networking & HTTP
  dio: ^5.7.0
  http: ^1.2.0

  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10

  # Date & Time
  intl: ^0.19.0

  # Validation & Formatting
  validators: ^3.0.0

  # Connectivity
  connectivity_plus: ^5.0.2

  # Notification
  flutter_local_notifications: ^18.0.1

  # Device Info
  device_info_plus: ^10.1.2

  # URL Launcher
  url_launcher: ^6.3.1

  # Logger
  logger: ^2.4.0

  # Utils
  get_it: ^7.6.0
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^4.0.0

  # Testing
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.7

  # Build
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
